root: true
env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:googlemaps/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: .
  project: ['./tsconfig.json']
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - googlemaps
rules:
  # react/prop-types: off
  react/react-in-jsx-scope: off # React v17 から import React 不要の設定
settings:
  react:
    version: detect
globals:
    google: readonly
