version: '3.9'

services:
  db:
    image: mysql:8.0.29
    container_name: db_pro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - mysql-data:/var/lib/mysql
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      # - /tmp/dockerdir:/etc/mysql/conf.d/
      - type: bind
        source: /tmp/dockerdir
        target: /etc/mysql/conf.d/
    ports:
      - 3306:3306

  api:
    build:
      context: ./api/
    container_name: api_pro
    environment:
      RAILS_ENV: production
    command: bash -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
    container_name: nginx_pro
    ports:
      - 80:80

volumes:
  mysql-data:
