version: '3.9'

services:
  db:
    image: mysql:8.0.29
    container_name: pro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - mysql-data:/var/lib/mysql
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    ports:
      - 3306:3306

  api:
    build:
      context: ./api/
    image: rkscz_pro_api
    container_name: pro_api
    environment:
      RAILS_ENV: production
    # command: bash -c "rm -f /api/tmp/pids/server.pid && DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:reset && bundle exec rails db:seed && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -p 3000 -c /api/config/unicorn.rb -E production"
    command: bash -c "bundle exec rails db:create && DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:reset && bundle exec rails db:seed && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -p 3000 -c /api/config/unicorn.rb -E production"
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  nginx:
    build:
      context: ./nginx/
    image: rkscz_pro_nginx
    container_name: pro_nginx
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  mysql-data:
