version: '3.8'

services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3306:3306

  api:
    build:
      context: ./api/
    command: bash -c "rm -f /api/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle install --path=vendor/bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
      - ./api/vendor/bundle:/api/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

  front:
    build:
      context: ./frontend/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - CI=true
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    command: sh -c "yarn && yarn start"
    ports:
      - 4000:3000
    # tty: true
    # stdin_open: true

volumes:
  mysql-data:
