version: 3.4
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al
            echo '^^^The files in your repo^^^'
            ls
            echo '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
            ls api
            echo '^^^^^^^^^^^^^^^^^^^^^^^^api^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
            ls frontend
            echo '^^^^^^^^^^^^^^^^^^^^^^^^frontend^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
            ls nginx
            echo '^^^^^^^^^^^^^^^^^^^^^^^^nginx^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
            cd api
            echo '^^^^^^^^^^^^^^^^^^^^^^^^rails^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
            bundle exec rails -v
            echo '^^^^^^^^^^^^^^^^^^^^^^^^rails^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
