default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: rekishichizu_development

test:
  <<: *default
  database: rekishichizu_test

production:
  <<: *default
  database: rekishichizu_production
  password: <%= ENV['RDS_DB_PASSWORD'] %>
  host: <%= ENV['RDS_DB_HOST'] %>
