source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'
gem 'rails', '~> 7.0.3', '>= 7.0.3.1'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'bootsnap', require: false
# CORS関連を簡単に設定できる
gem 'rack-cors'
# 環境変数を.envファイルで設定
gem 'dotenv-rails'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
end

group :development do
  gem 'rubocop', require: false
end

group :production do
  gem 'unicorn'
end
